mysite/main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.ingreso),
    path('homepage',
         views.homepage, name='homepage_get'),
    path('homepage/<int:user_id>/<int:articulo_id>',
         views.homepage, name='homepage_post'),
    path('carrito/<int:user_id>',
         views.carrito, name='carrito'),
    path('registro', views.registro, name='registro'),
    path('ingreso', views.ingreso, name='ingreso'),
    path('salir', views.salir, name='salir'),
    path('pagar', views.pagar, name='pagar'),
    path('cancelar', views.cancelar, name='cancelar'),
    path('pago', views.pago_exitoso, name='pago_exitoso'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

mysite/main/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
# Create your models here.


class Articulo(models.Model):
    id_articulo = models.IntegerField(primary_key=True)
    nombre_articulo = models.CharField(max_length=200)
    precio_articulo = models.IntegerField()
    url_imagen = models.CharField(max_length=500)

    ''' def __str__(self):
        return self.nombre_articulo '''


class Orden(models.Model):
    id_orden = models.IntegerField(primary_key=True)
    articulo = models.ForeignKey(
        Articulo,
        on_delete=models.CASCADE,
    )
    cantidad = models.IntegerField()
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

    valor_total = models.IntegerField()

    ''' def __str__(self):
        return self.id_orden '''

mysite/main/forms.py
from django import forms
from .models import Orden
from django.forms import ModelForm
from .models import Articulo
from django.contrib.auth.models import User


class OrdenForm(ModelForm):
    articulo = forms.ModelChoiceField(
        widget=forms.HiddenInput(), queryset=Articulo.objects.all())
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput(), queryset=User.objects.all())
    cantidad = forms.IntegerField(label='cantidad')
    valor_total = forms.IntegerField(
        label='valor_total', widget=forms.HiddenInput())

    ''' articulo = forms.IntegerField(widget=forms.HiddenInput(), required=False)
    user = forms.IntegerField(widget=forms.HiddenInput(), required=False) '''

    class Meta:
        model = Orden
        fields = ['articulo', 'cantidad', 'user', 'valor_total']

mysite/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Articulo
from .models import Orden
from django.contrib import messages
from .forms import OrdenForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
import requests
from requests.auth import HTTPBasicAuth
from django.conf import settings
import base64
from datetime import datetime, timedelta
import secrets
import json


# Create your views here.
def homepage(request, user_id=0, articulo_id=0):
    if request.method == 'POST':
        valor_total = 0
        articulo = Articulo.objects.get(id_articulo=articulo_id)
        precio_articulo = articulo.precio_articulo
        valor_total = int(precio_articulo) * int(request.POST['cantidad'])
        form = OrdenForm(request.POST.copy())
        form.data['user'] = user_id
        form.data['articulo'] = articulo_id
        form.data['valor_total'] = valor_total

        # check whether it's valid:
        if form.is_valid():
            form.save()
            messages.success(request, "Agregado con exito")
    else:
        form = OrdenForm()

    return render(request, "main/inicio.html", {"articulos": Articulo.objects.all, 'form': form})


def carrito(request, user_id):
    ordenes = Orden.objects.filter(user_id=user_id)
    tipos_articulos = Articulo.objects.all()
    factura = {}
    total_pagar = 0
    for tp in tipos_articulos:
        total = 0
        cantidad = 0
        ''' print(tp.id_articulo) '''
        for orden in ordenes:
            producto = Articulo.objects.get(id_articulo=orden.articulo_id)

            if tp.id_articulo == orden.articulo_id:
                factura[f'{producto.nombre_articulo}_{producto.id_articulo}'] = []
                total += int(orden.valor_total)
                cantidad += int(orden.cantidad)
                factura[f'{producto.nombre_articulo}_{producto.id_articulo}'].append({'url_imagen': producto.url_imagen, 'id_articulo': producto.id_articulo,
                                                                                      'total': total, 'cantidad': cantidad, 'nombre_articulo': producto.nombre_articulo})
        total_pagar += total

    return render(request, "main/carrito.html", {"factura": factura, "total_pagar": total_pagar})


def registro(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            usuario = form.save()
            nombre_usuario = form.cleaned_data.get('username')
            login(request, usuario)
            messages.success(
                request, f"{nombre_usuario} te has registrado con exito.")
            return redirect('main:homepage_get')
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg} {form.error_messages}")

    else:
        form = UserCreationForm()

    return render(request, "main/registro.html", {'form': form})


def ingreso(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            pdw = form.cleaned_data.get('password')
            user = authenticate(username=username, password=pdw)
            if user is not None:
                login(request, user)
                messages.info(request, f'Bienvenido {username}.')
                return redirect('main:homepage_get')
            else:
                messages.error(request, 'Error de contraseña o usuario.')
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg} {form.error_messages}")
    else:
        form = AuthenticationForm()
    return render(request, 'main/ingreso.html', {'form': form})


def salir(request):
    logout(request)
    messages.info(request, 'Saliste exitosamente')
    return redirect('main:ingreso')


def cancelar(request):
    id_user = request.GET['id_user']
    Orden.objects.filter(user_id=id_user).delete()
    ordenes = Orden.objects.filter(user_id=id_user)
    messages.error(request, 'Carrito Borrado')
    return redirect('main:homepage_get')


def pagar(request):

    if request.method == 'POST':
        id_user = request.POST['id_user']
        total_pagar = request.POST['total_pagar']
        url_pago = peticion_pago(total_pagar)
        if not url_pago:
            messages.error(request, 'Upps no se puede crear el pago')
            return redirect('main:homepage_get')
        else:
            return redirect(url_pago)


def crear_b64():
    to_b64 = f'{settings.TPAGA_USER}:{settings.TPAGA_PASSWORD}'
    texto = base64.b64encode(bytes(to_b64, 'utf-8'))
    return str(texto)


def peticion_pago(total_pagar):
    url_post_payment = settings.URL_PAYMENT
    idempotency_token = secrets.token_hex(16)
    expires_at = datetime.now() + timedelta(days=1)
    expires_at = expires_at.isoformat()
    data = {
        "cost": total_pagar,
        "purchase_details_url": "https://example.com/compra/348820",
        "voucher_url": "https://example.com/comprobante/348820",
        "idempotency_token": idempotency_token,
        "order_id": "348820",
        "terminal_id": "sede_45",
        "purchase_description": "Compra en My Store",
        "purchase_items": [
            {
                "name": "Aceite de girasol",
                "value": "13.390"
            },
            {
                "name": "Arroz X 80g",
                "value": "4.190"
            }
        ],
        "user_ip_address": "61.1.224.56",
        "expires_at": expires_at
    }

    data = json.dumps(data)
    headers = {
        'Content-Type': 'application/json'
    }

    peticion = requests.post(url_post_payment, data=data, headers=headers, auth=HTTPBasicAuth(
        settings.TPAGA_USER, settings.TPAGA_PASSWORD))

    if peticion.status_code != 201:
        return None

    res = peticion.json()
    return res['tpaga_payment_url']

def pago_exitoso(request):
    return render(request, 'main/pago_exitoso.html')

mysite/main/templates/main/carrito.html
{% extends 'main/principal.html'%} {% block content %}
<div class="row">
  <p>
    Para añadir mas articulos da click en:
    <a href="{% url 'main:homepage_get'%}">Productos</a>
  </p>
  {% for key, value in factura.items %} {% for v in value %}
  <div class="col s12 m6">
    <div class="card">
      <div class="card-image">
        <img src="{{v.url_imagen}}" />
        <span class="card-title">{{v.nombre_articulo}}</span>
      </div>
      <div class="card-content">
        <p>Total: ${{v.total}} COP.</p>
        <p>Cantidad: {{v.cantidad}}</p>
      </div>
    </div>
  </div>
  {%endfor%} {%endfor %}
</div>

<div class="row">
  <div class='col s12 m6'>
    <p>Total a PAGAR: ${{total_pagar}} COP.</p>
  </div>
</div>
<div class="row">
  <div class='col s12 m6'>
    <form action="{% url 'main:cancelar'%}" method='GET'>
      <input type="hidden" id="id_user" type="text" name="id_user" value="{{user.id}}">
      <button class="btn waves-effect waves-light" type="submit" name="action" style="width: 100%;">
        <i class="material-icons right">close</i> Cancelar
      </button>
    </form>
  </div>
</div>
<div class="row">
  <div class='col s12 m6'>
    <form action="{% url 'main:pagar'%}" method='POST'>
      {% csrf_token %}
      <input type="hidden" id="id_user" type="text" name="id_user" value="{{user.id}}">
      <input type="hidden" id="total_pagar" type="text" name="total_pagar" value="{{total_pagar}}">
      <button class="btn waves-effect waves-light" type="submit" name="action" style="width: 100%;">Pagar
        <i class="material-icons right">send</i>
      </button>
    </form>
  </div>
</div>
{% endblock %}

mysite/main/templates/main/includes/mensajes.html
{% if messages %} {% for message in messages%} {% if message.tags == 'success'%}
<script type="text/javascript">
  M.toast({
    html: "{{message}}",
    classes: "green rounded",
    displayLength: 1000,
  });
</script>

{% endif %} {% if message.tags == 'error'%}
<script type="text/javascript">
  M.toast({
    html: "{{message}}",
    classes: "red rounded",
    displayLength: 2000,
  });
</script>

{% endif %} {% if message.tags == 'info'%}
<script type="text/javascript">
  M.toast({
    html: "{{message}}",
    classes: "black rounded",
    displayLength: 2000,
  });
</script>

{% endif %} {% endfor %} {% endif %}

mysite/main/templates/main/includes/navbar.html
<nav>
    <div class="nav-wrapper blue darken-4 navbar-fixed">
        <a href="{% url 'main:homepage_get' %}" class="brand-logo">My Store</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        {% if user.is_authenticated %}
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="#">{{user.username}}</a></li>
            <li>
                <a href="{% url 'main:homepage_get'%}">Productos</a>
            </li>
            <li>
                <a href="{% url 'main:carrito' user_id=user.id %}">Carrito</a>
            </li>
            <li><a href="{% url 'main:salir' %}">Salir</a></li>
            {% else %}
            <a href="{% url 'main:ingreso' %}" class="brand-logo">My Store</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'main:registro' %}">Registro</a></li>
                <li><a href="{% url 'main:ingreso' %}">Ingreso</a></li>

            </ul>
            {% endif %}
    </div>
    <ul class="sidenav" id="mobile-demo">
        {% if user.is_authenticated %}
        <li><a href="#">{{user.username}}</a></li>
        <li>
            <a href="{% url 'main:homepage_get'%}">Productos</a>
        </li>
        <li>
            <a href="{% url 'main:carrito' user_id=user.id %}">Carrito</a>
        </li>
        <li><a href="{% url 'main:salir' %}">Salir</a></li>
        {% else %}
        <a href="{% url 'main:ingreso' %}" class="brand-logo">My Store</a>
        <ul id="nav-mobile">
            <li><a href="{% url 'main:registro' %}">Registro</a></li>
            <li><a href="{% url 'main:ingreso' %}">Ingreso</a></li>
        </ul>
        {% endif %}
    </ul>
</nav>

mysite/main/templates/main/ingreso.html
{% extends 'main/principal.html'%} {% block content %}
<h1>Ingreso</h1>
<div class="col s12 m6">
  <form action="" method="POST">
    {% csrf_token %} {{form.as_p}}
    <button type="submit">Enviar</button>
  </form>
</div>

Si no tienes una cuenta ve a <a href="{% url 'main:registro'%}">Registro</a> {% endblock %}

mysite/main/templates/main/inicio.html
{% extends 'main/principal.html'%} {% block content %}
<div class="row">
  {% for articulo in articulos %}
  <div class="col s12 m6">
    <div class="card">
      <div class="card-image">
        <img src="{{articulo.url_imagen}}" />
        <span class="card-title">{{articulo.nombre_articulo}}</span>
      </div>
      <div class="card-content">
        <p>Precio: ${{articulo.precio_articulo}} COP.</p>
      </div>
      <div class="card-action">
        <form action="{% url 'main:homepage_post' user_id=user.id articulo_id=articulo.id_articulo %}" method="POST">
          {% csrf_token %} {{ form }}

          <button class="btn waves-effect waves-light" type="submit" name="action">
            Agregar al carro
          </button>
        </form>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

mysite/main/templates/main/pago_exitoso.html
{% extends 'main/principal.html'%} {% block content %}
<div>
    <p>
    <h1>Pago exitoso<h1>
            </p>

</div>
{% endblock %}

mysite/main/templates/main/principal.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Import CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MY STORE</title>
</head>

<body>
    {% include "main/includes/navbar.html"%}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <!-- Import Scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>M.AutoInit();</script>
    {% include 'main/includes/mensajes.html'%}
</body>

</html>

mysite/main/templates/main/registro.html
{% extends 'main/principal.html'%}
{% block content %}
<h1>Registro</h1>
<div class="col s12 m6">
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Enviar</button>
    </form>
</div>

Si ya tienes una cuenta ve a <a href="{% url 'main:ingreso' %}">Ingresar</a>
{% endblock %}